// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ-MgUaPYnr50djYeLU4suKbeiesmlCfQ',
    appId: '1:367616043369:web:bc2953e57f31004c39b5f8',
    messagingSenderId: '367616043369',
    projectId: 'akillimutfak-d2968',
    authDomain: 'akillimutfak-d2968.firebaseapp.com',
    storageBucket: 'akillimutfak-d2968.firebasestorage.app',
    measurementId: 'G-YVB99LLJKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-6IpVuNGz0zmG-rbABIMwLmdstfMvq-M',
    appId: '1:367616043369:android:a2c411a716adc7ce39b5f8',
    messagingSenderId: '367616043369',
    projectId: 'akillimutfak-d2968',
    storageBucket: 'akillimutfak-d2968.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWlh0URXVTWYbSTgy8fK-5V7IBAbhi_Qg',
    appId: '1:367616043369:ios:ad8f236257de2a4039b5f8',
    messagingSenderId: '367616043369',
    projectId: 'akillimutfak-d2968',
    storageBucket: 'akillimutfak-d2968.firebasestorage.app',
    iosBundleId: 'com.example.akilliMutfak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWlh0URXVTWYbSTgy8fK-5V7IBAbhi_Qg',
    appId: '1:367616043369:ios:ad8f236257de2a4039b5f8',
    messagingSenderId: '367616043369',
    projectId: 'akillimutfak-d2968',
    storageBucket: 'akillimutfak-d2968.firebasestorage.app',
    iosBundleId: 'com.example.akilliMutfak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ-MgUaPYnr50djYeLU4suKbeiesmlCfQ',
    appId: '1:367616043369:web:7f314767420ed87139b5f8',
    messagingSenderId: '367616043369',
    projectId: 'akillimutfak-d2968',
    authDomain: 'akillimutfak-d2968.firebaseapp.com',
    storageBucket: 'akillimutfak-d2968.firebasestorage.app',
    measurementId: 'G-JR24YQ122G',
  );
}
